easy_admin:
  site_name: 'Inked France | Back Office'
  formats:
    datetime: 'd/m/Y H:m'
  design:
    form_theme:
        - '@EasyAdmin/form/bootstrap_4.html.twig'
        - '@FOSCKEditor/Form/ckeditor_widget.html.twig'
    menu:
       - { label: 'Voir le site', route: 'home', icon: 'laptop', target: '_blank'  }
       - { type: 'section', label: 'Gérer les publications' }
       - { entity: 'Article', icon: 'edit', label: 'Publications'  }
       - { entity: 'Category', icon: 'list' }
       - { type: 'section', label: 'Gérer les contacts' }
       - { entity: 'Contact', icon: 'envelope', label: 'Messages' }
       - { type: 'section', label: 'Gérer les utilisateurs' }
       - { entity: 'User', icon: 'user-secret' }
       - { type: 'section', label: 'Gérer les pages' }
       - { entity: 'Homepage', icon: 'home', label: 'Accueil' }
       - { entity: 'Contribute', icon: 'info', label: 'A propos' }
       - { entity: 'More', icon: 'book', label: 'Mentions Légales' }
  entities:
        Article:
            class: App\Entity\Article
            disabled_actions: ['new', 'show']
            label: "Publications"
            list:
              actions:
                - { name: 'edit', icon: 'pencil', label: false, css_class: 'btn btn-primary' }
                - { name: 'delete', icon: 'trash-alt', label: false, css_class: 'btn btn-danger' }
              fields:
                - { property: 'isPublished', type: 'toggle', label: 'Affichage Accueil' }
                - { property: 'title', type: 'fos_ckeditor', label: 'Titre' }
                - { property: 'photo', type: 'image', base_path: "%uploads_path%", label: 'Image' }
                - { property: 'updatedAt', label: 'Date' }
                - { property: 'category', label: 'Régions(s)' }
                - { property: 'content2', label: 'Description 2' }
                - { property: 'city', label: 'Ville' }
                - { property: 'author', label: 'Auteur' }
            form:
              help: "<i style='color: #4b6df5' class='fas fa-info-circle'></i> Attention ! Si vous modifiez l'adresse de la publication, vous risquez de perdre la géolocalisation ! Merci de modifier l'adresse directement depuis Mon Compte -> Mes Publications sur le site"
              fields:
                - { type: 'section', label: 'Classification' }
                - { property: 'category', label: 'Région(s)' }
                - { type: 'section', label: 'Informations' }
                - { property: 'title',type: 'fos_ckeditor', label: 'Titre' }
                - { property: 'content',type: 'fos_ckeditor', label: "Description" }
                - { property: 'content2',type: 'fos_ckeditor', label: 'Description 2' }
                - { property: 'photoFile', type: 'vich_image', base_path: 'uploads_path%', label: 'Image Principale' }
                - { type: 'section', label: 'Localisation' }
                - { property: 'address', label: 'Adresse' }
                - { property: 'city', label: 'Ville' }
                - { property: 'zipcode', label: 'Code postal' }
                - { type: 'section', label: 'Documents Complémentaires' }
                - { property: 'photoBFile', type: 'vich_image', base_path: 'uploads_path%', label: 'Image 2' }
                - { property: 'photoCFile', type: 'vich_image', base_path: 'uploads_path%', label: 'Image 3' }
                - { type: 'section', label: 'Contact' }
                - { property: 'telephone', label: 'Téléphone' }
                - { property: 'email', label: 'Email' }
                - { property: 'website', label: 'Site Web' }
        Category:
             class: App\Entity\Category
             label: "Régions"
             list:
                 actions:
                     - { name: 'edit', icon: 'pencil', label: false, css_class: 'btn btn-primary' }
                     - { name: 'delete', icon: 'trash-alt', label: false, css_class: 'btn btn-danger' }
                     - { name: 'new', icon: 'plus', label: 'Ajouter une région', css_class: 'btn btn-success' }
                 fields:
                     - { property: 'name', label: 'Nom de la région' }
             form:
                 fields:
                     - { property: 'name', label: 'Nom de la région' }
        Contribute:
               class: App\Entity\Abouts
               disabled_actions: ['delete', 'show']
               label: "A propos"
               list:
                 actions:
                   - { name: 'edit', icon: 'pencil', label: false, css_class: 'btn btn-primary' }
                 fields:
                   - { property: 'title', label: 'Titre' }
                   - { property: 'step1Title', label: 'Section 1' }
               form:
                   fields:
                     - { property: 'title',type: 'fos_ckeditor', label: 'Titre' }
                     - { type: 'section', label: 'Section 1' }
                     - { property: 'step1Title',type: 'fos_ckeditor', label: 'Titre' }
                     - { property: 'step1Body',type: 'fos_ckeditor', label: 'Contenu' }
                     - { property: 'step1ImgFile', type: 'vich_image', label: 'Image (.png, .jpeg)' }
        Homepage:
             class: App\Entity\Homepage
             disabled_actions: ['delete']
             label: "Page d'acceuil"
             list:
               actions:
                 - { name: 'edit', icon: 'pencil', label: false, css_class: 'btn btn-primary' }
               fields:
                 - { property: 'banner', type: 'image', label: 'Bannière', base_path: "%uploads_path%" }
                 - { property: 'goalTitle', label: 'Section 1' }
                 - { property: 'targetTitle', label: 'Section 2' }
                 - { property: 'approachTitle', label: 'Section 3' }
             form:
                 fields:
                   - { property: 'bannerFile', type: 'vich_image', label: 'Bannière' }
                   - { type: 'section', label: 'Section 1' }
                   - { property: 'goalTitle', type: 'fos_ckeditor', label: 'Titre' }
                   - { property: 'goalBody', type: 'fos_ckeditor', label: 'Contenu' }
                   - { type: 'section', label: 'Section 2' }
                   - { property: 'targetTitle',type: 'fos_ckeditor', label: 'Titre' }
                   - { property: 'targetTitle1',type: 'fos_ckeditor', label: 'Sous-titre Gauche' }
                   - { property: 'targetTitle2',type: 'fos_ckeditor', label: 'Sous-titre Droit' }
                   - { property: 'targetBody', type: 'fos_ckeditor', label: 'Texte Image Gauche' }
                   - { property: 'targetBody2', type: 'fos_ckeditor', label: 'Texte Image Droite' }
                   - { property: 'targetImgFile', type: 'vich_image', label: 'Image Gauche (.png, .jpeg)' }
                   - { property: 'targetImgPlaceFile', type: 'vich_image', label: ' Image Droite(.png, .jpeg)' }
                   - { type: 'section', label: 'Section 3' }
                   - { property: 'approachTitle',type: 'fos_ckeditor', label: 'Titre ' }
                   - { property: 'approachSubTitle',type: 'fos_ckeditor', label: 'Sous-titre' }
                   - { property: 'approachBody', type: 'fos_ckeditor', label: 'Contenu' }
        User:
            class: App\Entity\User
            disabled_actions: ['edit','new']
            label: "Utilisateurs"
            list:
              actions:
                - { name: 'show', icon: 'eye', label: false, css_class: 'btn btn-dark' }
                - { name: 'delete', icon: 'trash-alt', label: false, css_class: 'btn btn-danger' }
              fields:
                - { property: 'email', label: 'Email' }
                - { property: 'firstname', label: 'Prénom' }
                - { property: 'lastname', label: 'Nom' }
                - { property: 'city', label: 'Ville' }
                - { property: 'username', label: 'Pseudo' }
            show:
                fields:
                  - { property: 'email', label: 'Email' }
                  - { property: 'firstname', label: 'Prénom' }
                  - { property: 'lastname', label: 'Nom' }
                  - { property: 'gender', label: 'Genre' }
                  - { property: 'birthday', label: 'Date de naissance' }
                  - { property: 'profession', label: 'Profession' }
                  - { property: 'namevoie', label: 'Nom de la voie' }
                  - { property: 'channelnum', label: 'Numéro de voie' }
                  - { property: 'complement', label: 'Complément adresse' }
                  - { property: 'cp', label: 'Code postal' }
                  - { property: 'city', label: 'Ville' }
                  - { property: 'country', label: 'Pays' }
                  - { property: 'phone', label: 'Numéro Tel' }
                  - { property: 'mobile', label: ' Tel.mobile' }
                  - { property: 'hobbies', label: "Centre d'intérêts" }
                  - { property: 'username', label: 'Pseudo' }
                  - { property: 'avatar', type: 'image', base_path: '%uploads_path%' }
        Contact:
          class: App\Entity\Contact
          disabled_actions: ['edit','new']
          list:
            actions:
              - { name: 'delete', icon: 'trash-alt', label: false, css_class: 'btn btn-danger' }
            fields:
              - { property: 'email', label: 'Email' }
              - { property: 'name', label: 'Expéditeur' }
              - { property: 'subject', label: 'Sujet' }
              - { property: 'createdAt', label: 'Date de récéption' }
        More:
          class: App\Entity\More
          disabled_actions: ['show', 'new', 'delete']
          label: "Mentions Légales"
          list:
            actions:
              - { name: 'delete', icon: 'trash-alt', label: false, css_class: 'btn btn-danger' }
              - { name: 'edit', icon: 'pencil', label: false, css_class: 'btn btn-primary' }
            fields:
              - { property: 'titlecgu', label: 'CGU' }
              - { property: 'politicstitle', label: 'Politique de confidentialité' }
          form:
            fields:
              - { type: 'section', label: "Conditions Générales d'Utilisation" }
              - { property: 'titlecgu',type: 'fos_ckeditor', label: 'Titre CGU' }
              - { property: 'linkcgu', label: 'Lien CGU' }
              - { property: 'cgu',type: 'fos_ckeditor', label: 'Contenu CGU' }
              - { type: 'section', label: "Politique de Confidentialité" }
              - { property: 'politicstitle',type: 'fos_ckeditor', label: 'Titre Politique de Confidentialité' }
              - { property: 'politics',type: 'fos_ckeditor', label: 'Contenu Politique de confidentialité' }
